name: Express Server Build + Push

on:
  push:
    branches: [master]

jobs:
  # A job named "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest commit
      - name: checkout
        uses: actions/checkout@v2

      # Get the project version
      - name: get-version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      # Docker image is built
      - name: Docker Build
        run: docker build -t ghcr.io/krishnendudg/express-server-ghcr:${{ env.VERSION }} .

  # Uploading Docker Image
  upload:
    runs-on: ubuntu-latest

    needs: build

    steps:
      # Add checkout step first
      - name: checkout
        uses: actions/checkout@v2

      # ghcr Login
      - name: ghcr-login
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ secrets.USERNAME }} --password-stdin

      # Get the project version
      - name: get-version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      # Uploading the Image
      - name: ghcr-upload
        run: docker push ghcr.io/krishnendudg/express-server-ghcr:${{ env.VERSION }}
